### ISSUE TITLE
UIWebview usage in the jitsi framework

### ISSUE THREAD

**Issue by sampathed** [viking2917/cordova-plugin-jitsi-xcframework#1]
Apple is rejecting the version because of UIWebView. WKWebview is required. Help required to update you plugin replacing UIWebview to WKWebView

**Comment by viking2917** [comment]
Hi @sampathed. Couple of things:

1. The very first line of my Readme says this plugin doesn't work yet. I should probably make the repo private. I haven't figured out how to get it to work yet, I was trying to move to newest version of Jitsi which uses the new XCFramework mechanism for universal builds on iOS. But I repeat, t**his repo doesn't work yet**. 
2. So far as I know this repo, nor JITSI so far as i am aware, uses UIWebView. Are you sure you are not including that somehow in your project through some other means?

I am currently using this other repo in production, app has been approved by Apple: https://github.com/viking2917/cordova-plugin-jitsi. You are welcome to try it. It is a slightly older version of the JITSI SDK though.
